#ifndef FAKEKEYBOARD_GLOBAL_H
#define FAKEKEYBOARD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FAKEKEYBOARD_LIBRARY)
#  define FAKEKEYBOARDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FAKEKEYBOARDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FAKEKEYBOARD_GLOBAL_H
